language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    recipients:
      - pewniak747@gmail.com
      - bartosz.kopinski@netguru.pl

